language: c
compiler:
    - gcc
    - clang
os: linux

# Turn off sudo to run on container based infrastructure.
sudo: false

addons:
  apt:
    packages:
    - libfftw3-dev
    - libcunit1-dev

env:
  - WINDOW=kaiserbessel PRECISION=
  - WINDOW=gaussian PRECISION=
  - WINDOW=bspline PRECISION=
  - WINDOW=sinc PRECISION=
  - WINDOW=kaiserbessel PRECISION=--enable-float
  - WINDOW=gaussian PRECISION=--enable-float
  - WINDOW=bspline PRECISION=--enable-float
  - WINDOW=sinc PRECISION=--enable-float
  - WINDOW=kaiserbessel PRECISION=--enable-long-double
  - WINDOW=gaussian PRECISION=--enable-long-double
  - WINDOW=bspline PRECISION=--enable-long-double
  - WINDOW=sinc PRECISION=--enable-long-double

# Compile, link, and run tests.
script: ./bootstrap.sh && ./configure --with-window=$WINDOW $PRECISION --enable-all $(if test "$CC" = "clang"; then echo ""; else echo "--enable-openmp"; fi) && make && make check

## Print config.log for debugging.
after_failure: "cat config.log"

# Turn off email notifications.
notifications:
   email: false
